### ISSUE TITLE
토스페이 연동 - Order 테이블 생성

### ISSUE THREAD

**Issue by Lisiant** [TravelWONpick/TravelWONpick_server#17]
## 어떤 기능인가요?

>  토스페이먼츠 결제 요청 연동

### User 페이지 변경
- [x] User 필드 Sub 값 추가(상민님 기능 구현 충돌 반영)

### Order 추가

> ERD 상에서는 MySQL 의 `order` 가 예약어인 관계로 `orders` 테이블로 생성

사용자가 악의적으로 결제 금액을 수정하는 것을 방지하기 위해 Order 엔티티를 추가하여 결제 이전에 검증하는 로직을 추가 예정입니다.
- [x] orders - user 다대일 관계 (user 는 여러 개의 order 가질 수 있음)
- [x] order - reservation 일대일 관계 (하나의 order 당 하나의 reservation)
- [x] OrderController
- [x] OrderService
- [x] OrderRepository
- [x] PostOrderRequest, PostOrderResponse
- [x] User, Reservation 엔티티 수정

### 결제 요청 이전 검증
![image](https://github.com/user-attachments/assets/58409cb7-622b-4f65-a82b-ce875ab1f920)

https://docs.tosspayments.com/guides/v2/get-started/payment-flow#결제-정보-검증하기

**결제 요청 전에: 결제할 데이터 저장하기**
구매자의 결제 정보 결제 요청 전에 저장
- 결제 요청 전후 데이터 무결성 보장
- 적립금, 쿠폰 적용시 해당 내용도 저장(우리 프로젝트에서는 해당사항 없음)

orderId(주문번호)와 amount(최종 결제 금액)을 클라이언트에서 서버로 보내 임시로 저장합니다.

1. 구매자가 주문서에서 '결제하기' 버튼을 클릭해 결제를 요청.
2. 주문번호와 최종 결제 금액을 서버 세션이나 데이터베이스에 임시로 저장.
3. 결제 정보가 잘 저장되었다면 결제를 요청.

### 기타 작업 사항
- [x] BaseResponse 500 Internal Server Error 수정
- [x] 이에 따른 EventController 코드 수정
- [x]  ReservationRepository 생성

### TODO
- BaseResponse 패키지 경로 수정
- 결제 승인 로직 구현
